#MyLuaDebugger SSH login config. Stored per project root.
#Wed Jul 22 00:21:34 CST 2026
authType=password
host=82.157.199.25
localProjectPath=
openSshConfigPath=
openSshHost=
password=zynxf2702
port=22
privateKeyPassphrase=
privateKeyPath=
remotePath=/home/xilitian/workspace/luasourcecode/LuaSourceCode
user=xilitian
