#MyLuaDebugger SSH login config. Stored per project root.
#Tue Jul 21 23:55:23 CST 2026
authType=password
host=82.157.199.25
localProjectPath=
openSshConfigPath=
openSshHost=
password=zynxf2702
port=22
privateKeyPassphrase=
privateKeyPath=
remotePath=/home/xilitian/workspace/luasourcecode/LuaSourceCode
user=xilitian
